[tool]
name = "semantic-calculator"
description = "Semantic operations tool for vector and emoji calculations"
version = "0.1.0"
authors = ["Claude & Rob"]
repository = "https://github.com/yourusername/mcp-server-semantic-calc"
license = "MIT"

[tool.dependencies]
python = ">=3.8"
numpy = ">=1.20.0"
scikit-learn = ">=1.0.0"
sentence-transformers = ">=2.2.0"
torch = ">=1.10.0"
matplotlib = ">=3.4.0"
umap-learn = ">=0.5.2"
plotly = ">=5.5.0"
seaborn = ">=0.11.2"

[tool.scripts]
mcp = "semantic_calculator.__main__:main"
